apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: observability
spec:
  exporter:
    endpoint: http://otel-agent.observability.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'false'
      - name: OTEL_LOGS_EXPORTER
        value: none
      - name: OTEL_TRACES_EXPORTER
        value: otlp_proto_http
      - name: OTEL_METRICS_EXPORTER
        value: none