# The ambient profile enables ambient mode. The Istiod, CNI, and ztunnel charts must be deployed
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_HBONE: "true"
      ISTIO_META_ENABLE_HBONE_ACCESS_LOG: "true"

global:
  istioNamespace: istio-system
  variant: distroless

pilot:
  env:
    PILOT_ENABLE_AMBIENT: "true"
    PILOT_ENABLE_ALPHA_GATEWAY_API: "true"

# Not sure what the issue was, but I had to do: ln -s /var/lib/cni/bin/istio-cni /opt/cni/bin/istio-cni
cni:
  ambient:
    enabled: true
  chained: true       # leave Cilium as primary CNI
  cniBinDir: /opt/cni/bin
  cniConfDir: /etc/cni/net.d