apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-replicas-monitor
  namespace: observability
  labels:
    # `release: $HELM_RELEASE`: Prometheus can only detect PodMonitor with this label.
    release: kube-prometheus-stack
spec:
  jobLabel: ray-replicas
  # Only select Kubernetes Pods in the "default" namespace.
  namespaceSelector:
    matchNames:
      - ray
  # Only select Kubernetes Pods with "matchLabels".
  selector:
    matchLabels:
      ray.io/node-type: worker
  # A list of endpoints allowed as part of this PodMonitor.
  podMetricsEndpoints:
  - port: metrics