apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-hubble-monitor
  namespace: observability
  labels:
    # `release: $HELM_RELEASE`: Prometheus can only detect ServiceMonitor with this label.
    release: kube-prometheus-stack
spec:
  jobLabel: cilium-hubble-service
  # Only select Kubernetes Services in the "default" namespace.
  namespaceSelector:
    matchNames:
      - kube-system
  # Only select Kubernetes Services with "matchLabels".
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble
  # A list of endpoints allowed as part of this ServiceMonitor.
  endpoints:
    - port: hubble-metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - sourceLabels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          targetLabel: __address__
          regex: (.+)(?::\d+);(\d+)
          replacement: $1:$2
        # Keep and relabel the pod label "k8s-app" to Prometheus label "k8s_app"
        - sourceLabels: [__meta_kubernetes_pod_label_k8s_app]
          action: replace
          targetLabel: k8s_app